version: "3.9"

services:
  api:
    build:
      context: .
    image: vipartyom/flask-app
    ports:
      - 80:80
    volumes:
      - ./default_config.py:/code/docker_config.py
    depends_on:
      pg:
        condition: service_healthy
      migrations:
        condition: service_completed_successfully
  migrations:
    build:
      context: .
    image: vipartyom/flask-app
    volumes:
      - ./default_config.py:/code/docker_config.py
    depends_on:
      pg:
        condition: service_healthy
    command: flask db upgrade
  pg:
    image: postgres:latest
    environment:
      POSTGRES_USER: skypro
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: flask_app
    volumes:
      - ./pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      retries: 5
      timeout: 5s
