"""empty message

Revision ID: 79529d3f4dd2
Revises: 
Create Date: 2021-11-19 21:18:12.701230

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "79529d3f4dd2"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "movie",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=128)),
        sa.Column("description", sa.String(length=128)),
        sa.Column("trailer", sa.String(length=128)),
        sa.Column("year", sa.Integer()),
        sa.Column("rating", sa.Float()),
        sa.PrimaryKeyConstraint("id")
    )

    op.create_table(
        "director",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=128)),
        sa.PrimaryKeyConstraint("id")
    )

    op.create_table(
        "genre",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=128)),
        sa.PrimaryKeyConstraint("id")
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("movie")
    op.drop_table("director")
    op.drop_table("genre")
    # ### end Alembic commands ###
